# Generated by Django 3.0.8 on 2020-08-02 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200802_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(max_length=256, validators=[django.core.validators.URLValidator]),
        ),
    ]
